### PR TITLE
RFC: Use 1.46.0 as MSRV

### PR DESCRIPTION
**Pull request by jcgruenhage**
The manifest didn't specifically require any specific rust version and
the toolchain wasn't specified either. A MSRV was determined using
`cargo-msrv`, written to the main crate's cargo manifest and added to a
`rust-toolchain.toml` file. Additionally, the container images have been
adapted to use that specific rust version as well, to unify the used
rust version.

I don't have any strong opinions on this, but it'd probably make sense to decide on *something*, so that we can at least have some certainty for which features can be considered available. 1.46.0 is just the lowest that's currently supported, going higher for newer features would be nice IMO (there's quite a bit on https://caniuse.rs/ since 1.46.0), but again, no strong opinions here.

### CODE REVIEW

**Comment by Hirevo** [comment]
Hi, and thanks for the PR !

In the effort of purely getting the CI to run once again, I did increase the Rust version used in the various dockerfiles to 1.68 in PR **#139**, which is just the latest Rust version as of this writing.  

I'd like to thank you for having done the effort of bisecting the actual MSRV for the project.  
I did use, as part of some commits in **#117**, the new `let-else` statement syntax, which should make the MSRV to be at least 1.65 now.  

I think that syntax would be quite beneficial in simplifying some code right now, so I think I would want it to be at least 1.65 right now.
Maybe we can simply take this point in time to freeze the MSRV at 1.68, setup the CI to check that it holds true, and see where we go from here if there is some desirable feature to have ?

**Comment by jcgruenhage** [comment]
Going for >1.65 makes sense, yeah. Whether that's 1.68 specifically or something else, I don't really care.

**Comment by Hirevo** [comment]
I feel like since we're updating it anyway, we might as well pick the most recent version right now, so that would be 1.68.  
I'll make a separate PR with adding the additional CI check and mentioning the MSRV in the docs.  
You can tell me if you wish to update this PR for the changes in `Cargo.toml` and `rust-toolchain.toml`, otherwise I can easily add it to that subsequent PR.

**Comment by jcgruenhage** [comment]
It's probably easier for you to put it into your PR, I'll close this.

**Pull request closed without merging**
