### PR TITLE
External authentication methods

### PR DESCRIPTION
**Pull request by Hirevo**
This PR adds support for using GitHub and/or GitLab accounts to log in and/or register to an Alexandrie instance.  

Both of these two authentication methods can be configured or disabled individually.  
The original method of authentication (the manual one, with the password form) can now also be disabled, if desired.

Existing Alexandrie accounts can also be attached/detached to/from external accounts from within the frontend's account management panel.

Here are the new pieces of configuration that this PR adds support for:

```toml
[frontend.auth.local]
enabled = true
# Set`allow_registration` to false to prevent account creation using this method.
allow_registration = true

[frontend.auth.github]
enabled = false
client_id = "GITHUB_OAUTH_CLIENT_ID"
client_secret = "GITHUB_OAUTH_CLIENT_SECRET"
# Omit `allowed_organizations` to not require any organization membership.
allowed_organizations = [
    # Using this organization does not requires any specific team membership.
    { name = "ORG_NAME_1" },
    # But using this one does requires membership in one of specified teams.
    { name = "ORG_NAME_2", allowed_teams = ["TEAM_NAME"] },
]
allow_registration = true

[frontend.auth.gitlab]
enabled = false
origin = "https://gitlab.com"
client_id = "GITLAB_OAUTH_CLIENT_ID"
client_secret = "GITLAB_OAUTH_CLIENT_SECRET"
# Omit `allowed_groups` to not require any organization membership.
allowed_groups = [
    "GROUP_1",
    "GROUP_2",
]
allow_registration = true
```

### CODE REVIEW

**Comment by crookedview** [comment]
Hello,

Sorry if this is the wrong place to ask, but when adding this as an application to GitLab, what should the Callback URL be configured as?

**Comment by Hirevo** [comment]
@jcgruenhage Thanks for your feedback, and I am terribly sorry to have let you down with my absurd delay.  
Your solution is indeed the working fix that was needed.

I've now retested the features of this PR, with all backends and it did seem to work all fine.  
Everything seems ready to merge this PR except for the CI which cannot run because of the Docker images using Rust 1.50 (which is now too old for some dependencies).  
I've committed a fix in **#139**, but it seems that I'll need to rebase the PR for the CI to run with the updated version.

**Comment by Hirevo** [comment]
@crookedview I'm sorry for not having answered your question myself, I hope that finding the answer on your own wasn't too much of a pain.  
I'll try to enrich the documentation to make details like these more clear.

**Comment by Hirevo** [comment]
Additional docs have been added to clarify how to get the necessary OAuth credentials from GitHub and/or GitLab as well as which authorization callback URL to use for each of them.

**Comment by Hirevo** [comment]
I've added a check to avoid a user to accidentally remove its last authentication method (by not having a password set and detaching from its only external account).

The tests are passing, and the features work as expected in my testing.  
I think this looks good to be merged now.

**Pull request merged**
