### PR TITLE
Fix: sessions table contains registered users only

### PR DESCRIPTION
**Pull request by jerbs**
This fixes issue #118 .

### CODE REVIEW

**Comment by herkhinah** [comment]
Not adding unregistered users into the sessions table breaks error messages for not logged in users. To fix the issue without creating new ones use the following migration:
```

add following migration:

drop table "sessions";
create table "sessions" (
    "id" varchar(255) primary key,
    "author_id" bigint,
    "expiry" varchar(25) not null,
    "data" text not null,
    foreign key ("author_id") references "authors"("id") on update cascade on delete cascade
);
```

the issue wsa the datatype `bigserial` for `author_id` which has the constraint `not null`. `bigint` doesn't have that constraint.

**Comment by jerbs** [comment]
Updated the pull request as proposed by @herkhinah. All Rust modifications have been removed from the pull request.

**Review by Hirevo — APPROVED** [review]
Hi, thanks for the PR.  
I'm sorry for my too long delay to address this, it is quite a problematic bug.  
Thank you both for debugging the issue and contributing the solution !  

Due to changes in how GitHub handled running CI on repository forks, I can't run the CI right now without something like a rebase being done (GitHub doesn't let me approve the PR otherwise).  
But due to the changes being rather small, being purely SQL and having tested it on my end, I think it can be fine to bypass it for this PR.

**Comment by Hirevo** [comment]
I closed and re-opened the PR simply to cause the CI to re-run, it seemed that this was the only way to do it.

**Comment by Hirevo** [comment]
The CI statuses are all green, let's merge this PR.  

@jerbs @herkhinah Thank you both for the contribution !

**Pull request merged**
